version: "3.9"  # Or a later version

services:
  postgres:
    image: postgres:latest  # Or a specific version (e.g., postgres:15)
    container_name: my-postgres-container # Optional, but good practice
    restart: always # Ensures the container restarts if there's an issue
    ports:
      - "5432:5432" # Map port 5432 on the host to 5432 in the container (only needed for external access)
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword # **IMPORTANT: Use a strong password in production!**
      POSTGRES_DB: mydatabase
      # Add any other PostgreSQL environment variables here (e.g., PGDATA for data directory)
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data across container restarts
      # - ./init-scripts:/docker-entrypoint-initdb.d # Optional: For running initialization scripts

volumes:
  pgdata:  # Named volume for PostgreSQL data